name: Publish Docker image

on:
  push:
    branches:
      - 'develop'
    tags:
      - 'v*.*.*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: pagermon/pagermon
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: server/Dockerfile
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  push_to_registry_armhf:
    name: Push Docker image to Docker Hub - ARMHF
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: pagermon/pagermon
      
      - name: Build and push Docker image - ARMHF
        uses: docker/build-push-action@v2
        with:
          file: server/Dockerfile.armhf
          context: ./server
          platforms: linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}-armhf
